<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>PuntoCopa</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>

<div class="container">
    <div class="header">
        <h1 class="logo">PuntoCopa</h1>
        <h2 class="subtitulo">Conmebol Copa Libertadores</h2>
    </div>

    <div class="nav">
        <a href="index.php?action=categorias">Categorías</a>
        <a href="index.php?action=admin/categorias">Admin categorías</a>
        <a href="index.php?action=logout">Logout</a>
    </div>